name: Android Kotlin Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:  # 手动触发也可以

jobs:
  build:
    name: Build Android Kotlin App
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 JDK（Gradle 需要）
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 3️⃣ 授权 gradlew 可执行
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew



      # 6️⃣ （可选）构建 Release 版本
      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      # 7️⃣ 上传 Release APK 产物
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outp
